/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.44
 * Generated at: 2017-08-01 12:13:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Body.inventory_005ftransaction;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.connection.account.*;
import java.util.*;
import java.text.*;

public final class meteriallistvalue1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.connection.account");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String a=request.getParameter("count");
System.out.println(a);
Connection con=ConnectionDAO.getConnectionObject();
Statement smt=ConnectionDAO.createStatement(con);
ResultSet rs;
String sql="",matcode="",buffer="<table>",packing="",buffer1="",pur="", ins="";
int count=0;
double totalamount=0.00,totalaqty=0.00,totalfqty=0.00;
Vector<String> mrp=new Vector<String>();
Vector<String> scase=new Vector<String>();
Vector<String> spcs=new Vector<String>();
Vector<String> total=new Vector<String>();
Vector<String> slcase=new Vector<String>();
Vector<String> slpcs=new Vector<String>();
//Vector<String> tax = new Vector<String>();
//String sp[]=a.split("con");

String tax="";
DecimalFormat myFormatter = new DecimalFormat("00.00");
try
{
	//System.out.println("hello"+a);
	buffer=buffer+"<tr>  <th>M.R.P</th><th>ST. CASE</th><th>ST. PCS</th><th>TOTAL</th><th>SL. CASE</th><th>SL. PCS</th></tr>";
	sql="select count(matcode) from materialdetails where matcode=(select matcode from materialmaster where matname='"+a+"')";
	rs=smt.executeQuery(sql);
	System.out.println(sql);
	//System.out.println(sp[0]);
	while(rs.next())
	{
		count=rs.getInt(1);
	}
	if(count > 0)
	{
		sql="select * from materialdetails where matcode=(select matcode from materialmaster where matname='"+a+"')";
		//System.out.println(sql);
    	rs=smt.executeQuery(sql);
    	while(rs.next())
    	{
    		mrp.add(rs.getString(5));
    		scase.add(rs.getString(9));
    		spcs.add(rs.getString(10));
    		total.add(rs.getString(11));
    		slcase.add(rs.getString(3));
    		slpcs.add(rs.getString(4));
    		
    	}
    	for(int i=0;i<mrp.size();i++)
    	{
    		buffer=buffer+"<tr> <td><input type='text' name='formbean.mrp1' class='mrp1' value='"+mrp.get(i)+"' style='height:25px;border:1px solid #ccc;background:#FFFF99;width:110px;'/></td>  <td><input type='text' name='formbean.scase' class='scase' value='"+scase.get(i)+"' style='height:25px;border:1px solid #ccc;background:#FFFF99;width:110px;' onblur='exdt();'/></td>  <td><input type='text' name='formbean.spcs' class='spcs' value='"+spcs.get(i)+"' style='height:25px;border:1px solid #ccc;background:#FFFF99;width:110px;' onkeyup='calaqty();'/></td>  <td><input type='text' name='formbean.stotal' class='stotal' value='"+total.get(i)+"' style='height:25px;border:1px solid #ccc;background:#FFFF99;width:110px;' onkeyup='calfqty();'/></td> <td><input type='text' name='formbean.rtcase' class='rtcase' value='"+slcase.get(i)+"' style='height:25px;border:1px solid #ccc;background:#FFFF99;width:110px;' onkeyup=''/></td> <td><input type='text' name='formbean.rtpcs' class='rtpcs' value='"+myFormatter.format(Double.parseDouble(slpcs.get(i)))+"' style='height:25px;border:1px solid #ccc;background:#FFFF99;width:110px;' onkeyup='calamount();calpopupamount();' onblur='calforvat();'/></td>  <td><input type='button' value='SELECT' class='butStnd' onclick='PersonViewModel(this);copyvalue();fadeout();'/></td> </tr>"; 
    	}
    	
    	sql="select packing,type_tax,pur_ac,matcode from materialmaster where matname='"+a+"' ";
    	//System.out.println(buffer1);
    	rs=smt.executeQuery(sql);
    	while(rs.next())
    	{
    		packing=rs.getString(1);
    		tax=rs.getString(2);
    		pur=rs.getString(3);
    		ins=rs.getString(4);
    	}
    	
    	
	}
	else if(count == 0) 
	{
		buffer=buffer+"<tr> <td><input type='text' name='formbean.mrp1' class='mrp1' value='' style='height:25px;border:1px solid #ccc;background:#FFFF99;width:110px;'/></td>  <td><input type='text' name='formbean.scase' class='scase' value='' style='height:25px;border:1px solid #ccc;background:#FFFF99;width:110px;' onblur='exdt();'/></td>  <td><input type='text' name='formbean.spcs' class='spcs' value='' style='height:25px;border:1px solid #ccc;background:#FFFF99;width:110px;' onkeyup='calaqty();'/></td>  <td><input type='text' name='formbean.stotal' class='stotal' value='' style='height:25px;border:1px solid #ccc;background:#FFFF99;width:110px;' onkeyup='calfqty();'/></td> <td><input type='text' name='formbean.rtcase' class='rtcase' value='' style='height:25px;border:1px solid #ccc;background:#FFFF99;width:110px;' onkeyup=''/></td> <td><input type='text' name='formbean.rtpcs' class='rtpcs' value='' style='height:25px;border:1px solid #ccc;background:#FFFF99;width:110px;' onkeyup='calamount();calpopupamount();' onblur='calforvat();'/></td>   <td><input type='button' value='No Rows' class='butStnd' onclick='fadeout();PersonViewModel(this);'/></td> </tr>"; 
    }
	
	
	buffer=buffer+"</table>";
	
	System.out.println("ami jeta chai: "+tax );
	
	buffer1=buffer+"bubun"+packing+"bubun"+tax+"bubun"+pur+"bubun"+ins;
	System.out.println(buffer1);
	out.print(buffer1);
}
catch(Exception error)
{
	System.out.println("error found on merialdetails jsp "+error);
}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
