/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.44
 * Generated at: 2017-08-08 10:35:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.connection.account.*;
import java.util.*;

public final class printdetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.connection.account");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\r\n");
      out.write("<title>Jobwork Entry</title>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"js/tablefilter.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style2.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/draftbutton.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/printbutton.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/breadcumbs.css\" ></link>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("            function printDiv(divName) {\r\n");
      out.write("                  var printContents = document.getElementById(divName).innerHTML;\r\n");
      out.write("                  var originalContents = document.body.innerHTML;\r\n");
      out.write("                 \r\n");
      out.write("                  document.body.innerHTML = printContents;\r\n");
      out.write(" \r\n");
      out.write("                  window.print();\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("                  document.body.innerHTML = originalContents;\r\n");
      out.write("            }\r\n");
      out.write(" \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("table.gridtable {\r\n");
      out.write("\tfont-family: verdana,arial,sans-serif;\r\n");
      out.write("\tfont-size:11px;\r\n");
      out.write("\tcolor:#333333;\r\n");
      out.write("\tborder-width: 1px;\r\n");
      out.write("\tborder-color: #666666;\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("table.gridtable th {\r\n");
      out.write("\tborder-width: 1px;\r\n");
      out.write("\tpadding: 8px;\r\n");
      out.write("\tborder-style: solid;\r\n");
      out.write("\tborder-color: #666666;\r\n");
      out.write("\tbackground-color: #dedede;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.gridtable tr {\r\n");
      out.write("\tborder-width: 1px;\r\n");
      out.write("\tpadding: 8px;\r\n");
      out.write("\tborder-style: solid;\r\n");
      out.write("\tborder-color: #666666;\r\n");
      out.write("\tbackground-color: #ffff;\r\n");
      out.write("}\r\n");
      out.write("table.gridtable td {\r\n");
      out.write("\tborder-width: 1px;\r\n");
      out.write("\tpadding: 8px;\r\n");
      out.write("\tborder-style: solid;\r\n");
      out.write("\tborder-color: #666666;\r\n");
      out.write("\tbackground-color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("table.imagetable {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tfont-family: verdana,arial,sans-serif;\r\n");
      out.write("\tfont-size:11px;\r\n");
      out.write("\tcolor:#000;\r\n");
      out.write("\tborder-width: 1px;\r\n");
      out.write("\tborder-top:1px solid #c6d5e1;\r\n");
      out.write("\tborder-bottom:1px solid #c6d5e1;\r\n");
      out.write("\tborder-right:1px solid #c6d5e1;\r\n");
      out.write("\tborder-left:1px solid #c6d5e1;\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("table.imagetable th {\r\n");
      out.write("\t\r\n");
      out.write("\tbackground:url(images/header-bg.gif);\r\n");
      out.write("\tborder-width: 1px;\r\n");
      out.write("\tpadding:4px 6px 6px;\r\n");
      out.write("\tcolor:#fff;\r\n");
      out.write("\tborder-top:1px solid #c6d5e1;\r\n");
      out.write("\tborder-bottom:1px solid #c6d5e1;\r\n");
      out.write("\tborder-right:1px solid #c6d5e1;\r\n");
      out.write("\tborder-left:1px solid #c6d5e1;\r\n");
      out.write("\tborder-style: solid;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("table.imagetable td {\r\n");
      out.write("\ttext-decoration:none;\r\n");
      out.write("\tborder-width: 1px;\r\n");
      out.write("\tpadding:4px 6px 6px;\r\n");
      out.write("\tborder-top:1px solid #c6d5e1;\r\n");
      out.write("\tborder-bottom:1px solid #c6d5e1;\r\n");
      out.write("\tborder-right:1px solid #c6d5e1;\r\n");
      out.write("\tborder-left:1px solid #c6d5e1;\r\n");
      out.write("\tborder-style: solid;\r\n");
      out.write("\tbackground-color: #ffffff;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("*{ margin:0; padding:0;}\r\n");
      out.write("body{ font-family:Verdana, Geneva, sans-serif; font-size:14px;}\r\n");
      out.write(".container{ width:1100px; margin:auto;}\r\n");
      out.write("p { padding:2px 3px;}\r\n");
      out.write(".padding_left { padding-left:100px !important;}\r\n");
      out.write(".one h1 { font-size:18px;}\r\n");
      out.write(".one_middle p:nth-child(n+3) { margin-top:20px;}\r\n");
      out.write(".one_middle p:last-child { margin-top:30px; padding-bottom:10px; font-size:15px; font-weight:600;}\r\n");
      out.write(".one_left p:last-child { padding-bottom:20px; }\r\n");
      out.write(".one .one_right p:nth-child(1) { margin-top:30px;}\r\n");
      out.write(".one .one_right p:nth-child(1) span{ padding-left:30px;}\r\n");
      out.write(".one .one_right p:nth-child(2) span{ padding-left:78px;}\r\n");
      out.write(".one .one_right p:nth-child(3) span{ padding-left:49px;}\r\n");
      out.write(".one .one_right p:nth-child(4) span{ padding-left:78px;}\r\n");
      out.write(".one .one_right p:nth-child(5) span{ padding-left:4px;}\r\n");
      out.write(".one tr td, .two tr td, .three tr td {border-bottom: 1px dashed #000;}\r\n");
      out.write(".two_left p:nth-child(2) { margin-top:70px;}\r\n");
      out.write(".two_right p { border-left:1px solid #000; margin:5px 0px; padding-left:5px;}\r\n");
      out.write(".two {padding: 4px 0px;}\r\n");
      out.write(".two .two_right p:nth-child(1) span{ padding-left:20px;}\r\n");
      out.write(".two .two_right p:nth-child(2) span{ padding-left:38px;}\r\n");
      out.write(".two .two_right p:nth-child(3) span{ padding-left:48px;}\r\n");
      out.write(".two .two_right p:nth-child(4) span{ padding-left:61px;}\r\n");
      out.write(".two .two_right p:nth-child(5) span{ padding-left:50px;}\r\n");
      out.write(".three tr td { padding-bottom:2px;}\r\n");
      out.write(".three tr:nth-child(n+2) td { border-bottom:none;}\r\n");
      out.write(".three p { font-size:12px; padding-top:2px; padding-bottom:2px;  border-left:1px solid #000;}\r\n");
      out.write(".three tr:nth-child(n+2) p {border:none;}\r\n");
      out.write(".three tr td{ margin:3px 0px;}\r\n");
      out.write(".three h3 { font-size:14px; padding:3px 2px;}\r\n");
      out.write(".three tr:last-child td {border-top:1px dashed #000000; border-bottom:1px dashed #000000;}\r\n");
      out.write(".four p { font-size:12px;}\r\n");
      out.write(".four { padding:5px 0px;}\r\n");
      out.write(".four_paragraph { text-align:justify; padding-right:25px;}\r\n");
      out.write(".border_left{ border-left:1px solid #000000; margin:2px 0px; padding-left:5px;}\r\n");
      out.write(".border_top { border-top:1px dashed #000000;  padding-left:5px; }\r\n");
      out.write("\r\n");
      out.write(".five tr td { border-bottom:1px dashed #000000; border-top:1px dashed #000000;}\r\n");
      out.write(".five tr td { padding:5px 0px;}\r\n");
      out.write(".six tr:last-child td { border-bottom:1px dashed #000000;}\r\n");
      out.write(".six .six_right td{ padding:30px 0px 5px 0px;}\r\n");
      out.write(".six .six_left td { padding-top:10px;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<sj:head/>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#ui-datepicker-div {background:#dce6ee;}\r\n");
      out.write("\r\n");
      out.write("#ui-datepicker-div .ui-state-highlight {color: #dce6ee;}\r\n");
      out.write("\r\n");
      out.write("#ui-datepicker-div.ui-datepicker-control {background: blue;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".ui-dialog-titlebar{ \r\n");
      out.write("    background: #FFCC66 repeat-x;\r\n");
      out.write("    color:#fff;      \r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body><center>\r\n");
      out.write("<!--       \r\n");
      out.write("\t\tjava.util.Date dt = new java.util.Date();\r\n");
      out.write("\t\t//final String td = (dt.getYear() + 1900) + \"-\" + (dt.getMonth() + 1)+ \"-\" + dt.getDate();\r\n");
      out.write("\t\tfinal String td = dt.getDate()+\"/\"+(dt.getMonth() + 1)+\"/\"+(dt.getYear() + 1900);\r\n");
      out.write(" -->\r\n");
      out.write("\t");
		String packing2="",casep2="",pcs2="",freepcs2="",mrp2="",rate2="",amount2="",disc2="",discp2="",discamt2="",grossamt2="",gst2="", gstamt2="";
   			String area = "", salesmanname = "",retailername="",memono="",address="",date="",placename="",partyname="",pgstinno="", voucher_no="";
			String packing = "", case1 = "", pcs1 = "", free = "",mrp = "", rate1 = "", amt = "",gst1 = "",gstamt = "",totalamt ="",total="",grossamt="",sgst="",cgst="",igst="",add1="", netamt="";
			String nameofitem="";
			String user = request.getParameter("value");
			int cou=0;
			double tot1=0;
			System.out.println("user :"+user);
			Connection conn = ConnectionDAO.getConnectionObject();
			Statement stm = ConnectionDAO.createStatement(conn);
			ResultSet rs=null;
			String sql = "select * from itransaction where id='"+user+"' order by id desc";

			try {

				 rs = stm.executeQuery(sql);

					while (rs.next()) {
					voucher_no = rs.getString(2);
					area = rs.getString(4);
					salesmanname = rs.getString(6);
					retailername = rs.getString(7);
					date = rs.getString(5);
					memono = rs.getString(8); 
					address = rs.getString(13);
					total = rs.getString(14);
					grossamt= rs.getString(16);
					cgst = rs.getString(20);
					sgst = rs.getString(19);
					igst = rs.getString(21);
					add1 = rs.getString(25);
					netamt = rs.getString(26);
				}
					
					sql= "Select placename from placemaster where placecode ='"+area+"'";
					 rs = stm.executeQuery(sql);
					 System.out.println(sql+","+voucher_no);

					while (rs.next()) {
						placename = rs.getString(1);
					}
					sql= "Select party_name, gstinno from partymaster1 where party_code ='"+retailername+"'";
					//System.out.println(sql);
					rs = stm.executeQuery(sql);
				

					while (rs.next()) {
						partyname = rs.getString(1);
						pgstinno = rs.getString(2);
					}
					sql= "Select * from idetails where voucherno ='"+voucher_no+"'";
					rs = stm.executeQuery(sql);
					

					while (rs.next()) {
						packing = rs.getString(20);
						case1 = rs.getString(4);
						pcs1 = rs.getString(5);
						free = rs.getString(6);
						mrp = rs.getString(7);
						rate1 = rs.getString(8);
						amt = rs.getString(11);
						gst1 = rs.getString(24);
						gstamt = rs.getString(19);
						totalamt = rs.getString(15);
					}

			} catch (Exception e) {

			}
			
		
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"printableArea\">\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"container\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"one\">\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td align=\"left\" valign=\"bottom\" class=\"one_left\">\r\n");
      out.write("                    <p>D.L.No. : 30 (20A) & 30A(20B) </p>\r\n");
      out.write("                    <p>Edible Oil Lic.No. 16/HzB </p>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td align=\"center\" valign=\"top\" class=\"one_middle\">\r\n");
      out.write("                    <h1>PODDAR VARIETY STORES</h1>\r\n");
      out.write("                    <p>GOLA ROAD, RAMGARH CANTT - 829122,DIST- HAZARIBAGH.</p>\r\n");
      out.write("                    <p>( O R I G I N A L ) </p>\r\n");
      out.write("                    <p>TAX INVOICE</p>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td align=\"left\" valign=\"middle\" class=\"one_right\">\r\n");
      out.write("                    <p>Phone <span>:</span></p>\r\n");
      out.write("                    <p> GSTIN No.<span>");
      out.print(pgstinno);
      out.write("</span></p>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        \r\n");
      out.write("        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"two\">\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td width=\"50%\" align=\"left\" valign=\"top\" class=\"two_left\">\r\n");
      out.write("                <p>To,<br>S.D.SINGH </p>\r\n");
      out.write("                <p>GSTIN No :<span>");
      out.print(pgstinno);
      out.write("</span></p>\r\n");
      out.write("                </td>\r\n");
      out.write("                \r\n");
      out.write("                <td width=\"50%\" align=\"left\" valign=\"top\" class=\"two_right\">\r\n");
      out.write("                    <p>Memo Number: <span>");
      out.print(memono);
      out.write("</span> </p>\r\n");
      out.write("                    <p>Invoice date: <span>");
      out.print(date);
      out.write("</span></p>\r\n");
      out.write("                    <p>Area Name: <span>");
      out.print(placename);
      out.write("</span></p>\r\n");
      out.write("                    <p>Category: <span>: CASH </span><span class=\"padding_left\">AMMENDED</span></p>\r\n");
      out.write("                    <p>Booked By: <span>");
      out.print(partyname);
      out.write("</span> </p>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        \r\n");
      out.write("    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"three\">\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td width=\"20%\" align=\"left\" valign=\"middle\"><h3>PARTICULARS </h3></td>\r\n");
      out.write("            <td width=\"7%\" align=\"center\" valign=\"middle\"><p>HSN CODE</p></td>\r\n");
      out.write("            <td width=\"4%\" align=\"center\" valign=\"middle\"><p>PACK</p></td>\r\n");
      out.write("            <td width=\"4%\" align=\"center\" valign=\"middle\"><p>CASE</p></td>\r\n");
      out.write("            <td width=\"4%\" align=\"center\" valign=\"middle\"><p>PCS.</p></td>\r\n");
      out.write("            <td width=\"4%\" align=\"center\" valign=\"middle\"><p>FREE</p></td>\r\n");
      out.write("            <td width=\"4%\" align=\"center\" valign=\"middle\"><p>M.R.P.</p></td>\r\n");
      out.write("            <td width=\"4%\" align=\"center\" valign=\"middle\"><p>RATE</p></td>\r\n");
      out.write("            <td width=\"6%\" align=\"center\" valign=\"middle\"><p>AMOUNT</p></td>\r\n");
      out.write("            <td width=\"4%\" align=\"center\" valign=\"middle\"><p>CSH/CS</p></td>\r\n");
      out.write("            <td width=\"4%\" align=\"center\" valign=\"middle\"><p>SCH.%</p></td>\r\n");
      out.write("            <td width=\"6%\" align=\"center\" valign=\"middle\"><p>SCH.AMT</p></td>\r\n");
      out.write("            <td width=\"8%\" align=\"center\" valign=\"middle\"><p>GR AMOUNT</p></td>\r\n");
      out.write("            <td width=\"5%\" align=\"center\" valign=\"middle\"><p>GST @</p></td>\r\n");
      out.write("            <td width=\"6%\" align=\"center\" valign=\"middle\"><p>GST AMT</p></td>\r\n");
      out.write("            <td width=\"11%\" align=\"right\" valign=\"middle\"><p>TOTAL AMOUNT</p></td>\r\n");
      out.write("\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("\t   ");
 sql= "SELECT COUNT(voucherno) from idetails where voucherno ='"+voucher_no+"'" ;

	   	try{
	   
	 	   rs= stm.executeQuery(sql);
	 		 System.out.println(sql);
	 	 while (rs.next()) {
			 		 System.out.println("hi");
					cou = rs.getInt(1);
					System.out.println("hi:"+cou);
	 						 }
	  			 
	  			 	sql="(select nameitem from itransaction where voucherno='"+voucher_no+"') ";
				   	sql= "Select * from idetails where voucherno ='"+voucher_no+"'";
        			 System.out.println(sql);
					 rs = stm.executeQuery(sql);
					 while(rs.next())
					 {
					    nameofitem=rs.getString(3);
					    packing2=rs.getString(20);
					    casep2=rs.getString(4);
						pcs2=rs.getString(5);
						freepcs2=rs.getString(6);
						mrp2=rs.getString(7);
						rate2=rs.getString(8);
						amount2=rs.getString(11);
						disc2=rs.getString(9);
						discp2=rs.getString(10);
						discamt2=rs.getString(16);
						grossamt2=rs.getString(17);
						gst2=rs.getString(18);
						gstamt2=rs.getString(19);
						tot1=Double.parseDouble(grossamt2)+Double.parseDouble(gstamt2);
						
					 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t <tr>\r\n");
      out.write("\t\t\t\t            <td width=\"20%\" align=\"left\" valign=\"middle\"><p>");
      out.print(nameofitem);
      out.write("</p></td>\r\n");
      out.write("\t\t\t\t            <td width=\"7%\" align=\"center\" valign=\"middle\"><p></p></td>\r\n");
      out.write("\t\t\t\t            <td width=\"4%\" align=\"center\" valign=\"middle\"><p>");
      out.print(packing2);
      out.write("</p></td>\r\n");
      out.write("\t\t\t\t            <td width=\"4%\" align=\"center\" valign=\"middle\"><p>");
      out.print(casep2);
      out.write("</p></td>\r\n");
      out.write("\t\t\t\t            <td width=\"4%\" align=\"center\" valign=\"middle\"><p>");
      out.print(pcs2);
      out.write("</p></td>\r\n");
      out.write("\t\t\t\t            <td width=\"4%\" align=\"center\" valign=\"middle\"><p>");
      out.print(freepcs2);
      out.write("</p></td>\r\n");
      out.write("\t\t\t\t            <td width=\"4%\" align=\"center\" valign=\"middle\"><p>");
      out.print(mrp2);
      out.write("</p></td>\r\n");
      out.write("\t\t\t\t            <td width=\"4%\" align=\"center\" valign=\"middle\"><p>");
      out.print(rate2);
      out.write("</p></td>\r\n");
      out.write("\t\t\t\t            <td width=\"6%\" align=\"center\" valign=\"middle\"><p>");
      out.print(amount2);
      out.write("</p></td>\r\n");
      out.write("\t\t\t\t            <td width=\"4%\" align=\"center\" valign=\"middle\"><p>");
      out.print(disc2);
      out.write("</p></td>\r\n");
      out.write("\t\t\t\t            <td width=\"4%\" align=\"center\" valign=\"middle\"><p>");
      out.print(discp2);
      out.write("</p></td>\r\n");
      out.write("\t\t\t\t            <td width=\"6%\" align=\"center\" valign=\"middle\"><p>");
      out.print(discamt2);
      out.write("</p></td>\r\n");
      out.write("\t\t\t\t            <td width=\"8%\" align=\"center\" valign=\"middle\"><p>");
      out.print(grossamt2);
      out.write("</p></td>\r\n");
      out.write("\t\t\t\t            <td width=\"5%\" align=\"center\" valign=\"middle\"><p>");
      out.print(gst2);
      out.write("</p></td>\r\n");
      out.write("\t\t\t\t            <td width=\"6%\" align=\"center\" valign=\"middle\"><p>");
      out.print(gstamt2);
      out.write("</p></td>\r\n");
      out.write("\t\t\t\t            <td width=\"11%\" align=\"right\" valign=\"middle\"><p>");
      out.print(tot1);
      out.write("</p></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t        </tr>\r\n");
      out.write("\t\t\t\t\t");
 }
					
	   			
	   	  
         
       } 
		catch(Exception e)
		{
			e.printStackTrace();
		}
	   	ConnectionDAO.closeConnection(conn);
       
      out.write("\r\n");
      out.write("       \t\r\n");
      out.write("       \t        </tr>\r\n");
      out.write(" </table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"four\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"43%\" rowspan=\"5\" align=\"left\" valign=\"top\"><p class=\"four_paragraph\">We hereby certify that goods mentioned in this memo are warranted to be the same in nature substance and quality as demanded by the vender. Above rates are inclusive of delivery charges. </p></td>\r\n");
      out.write("    <td width=\"6%\" align=\"center\" valign=\"top\" ><p class=\"border_left\">GST @</p></td>\r\n");
      out.write("    <td width=\"9%\" align=\"center\" valign=\"top\"><p>ON AMOUNT:</p></td>\r\n");
      out.write("    <td width=\"7%\" align=\"center\" valign=\"top\"><p>SGST AMT:<span>");
      out.print(sgst);
      out.write("</span></p></td>\r\n");
      out.write("    <td width=\"7%\" align=\"center\" valign=\"top\"><p>CGST AMT:<span>");
      out.print(cgst);
      out.write("</span></p></td>\r\n");
      out.write("    <td width=\"7%\" align=\"center\" valign=\"top\"><p>IGST AMT:<span>");
      out.print(igst);
      out.write("</span></p></td>\r\n");
      out.write("    <td width=\"10%\" align=\"left\" valign=\"top\"><p class=\"border_left\">Total&nbsp;Gross&nbsp;Amount:</p></td>\r\n");
      out.write("     <td width=\"1%\" align=\"center\" valign=\"top\"><p></p></td>\r\n");
      out.write("    <td width=\"9%\" align=\"right\" valign=\"top\"><p><span>");
      out.print(grossamt);
      out.write("</span></p></td>\r\n");
      out.write("  \r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"10%\" align=\"right\" valign=\"top\"><p>3367.35</p></td>\r\n");
      out.write("    <td width=\"6%\" align=\"center\" valign=\"top\" ><p class=\"border_left\"> 05.00</p></td>\r\n");
      out.write("    <td width=\"9%\" align=\"center\" valign=\"top\"><p>448.67</p></td>\r\n");
      out.write("    <td width=\"7%\" align=\"center\" valign=\"top\"><p>65.06</p></td>\r\n");
      out.write("    <td width=\"7%\" align=\"center\" valign=\"top\"><p></p></td>\r\n");
      out.write("    <td width=\"7%\" align=\"center\" valign=\"top\"><p></p></td>\r\n");
      out.write("    <td width=\"10%\" align=\"left\" valign=\"top\"><p class=\"border_left\">&nbsp;</p></td>\r\n");
      out.write("    <td width=\"1%\" align=\"center\" valign=\"top\"></td>\r\n");
      out.write("    <td width=\"10%\" align=\"right\" valign=\"top\"><p></p></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("  <td width=\"6%\" align=\"center\" valign=\"top\"><p class=\"border_left\"> 12.00</p></td>\r\n");
      out.write("    <td width=\"9%\" align=\"center\" valign=\"top\"><p>2704.86</p></td>\r\n");
      out.write("    <td width=\"7%\" align=\"center\" valign=\"top\"><p>148.76</p></td>\r\n");
      out.write("    <td width=\"7%\" align=\"center\" valign=\"top\"><p></p></td>\r\n");
      out.write("    <td width=\"7%\" align=\"center\" valign=\"top\"><p></p></td>\r\n");
      out.write("    <td width=\"13%\" align=\"left\" valign=\"top\"><p class=\"border_left\">Rounding Off (Less):</p></td>\r\n");
      out.write("    <td width=\"1%\" align=\"center\" valign=\"top\"><p></p></td>\r\n");
      out.write("    <td width=\"9%\" align=\"right\" valign=\"top\"><p><span>");
      out.print(add1);
      out.write("</span></p></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"6%\" align=\"center\" valign=\"top\"><p class=\"border_left\"> 18.00</p></td>\r\n");
      out.write("    <td width=\"9%\" align=\"center\" valign=\"top\"><p></p></td>\r\n");
      out.write("    <td width=\"7%\" align=\"center\" valign=\"top\"><p></p></td>\r\n");
      out.write("    <td width=\"7%\" align=\"center\" valign=\"top\"><p></p></td>\r\n");
      out.write("    <td width=\"7%\" align=\"center\" valign=\"top\"><p></p></td>\r\n");
      out.write("    <td width=\"10%\" rowspan=\"2\" align=\"left\" valign=\"bottom\"><p class=\"border_top\">Net Amount:</p></td>\r\n");
      out.write("    <td width=\"1%\" align=\"center\" valign=\"top\"><p >&nbsp; </p></td>\r\n");
      out.write("    <td width=\"10%\" rowspan=\"2\" align=\"right\" valign=\"bottom\"><p class=\"border_top\"><span>");
      out.print(netamt);
      out.write("</span></p></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"6%\" align=\"center\" valign=\"top\"><p class=\"border_left\">28.00</p></td>\r\n");
      out.write("    <td width=\"9%\" align=\"center\" valign=\"top\"><p>ON AMOUNT</p></td>\r\n");
      out.write("    <td width=\"7%\" align=\"center\" valign=\"top\"><p>SGST AMT</p></td>\r\n");
      out.write("    <td width=\"7%\" align=\"center\" valign=\"top\"><p>CGST AMT</p></td>\r\n");
      out.write("    <td width=\"7%\" align=\"center\" valign=\"top\"><p>IGST AMT</p></td>\r\n");
      out.write("    <td width=\"1%\" align=\"center\" valign=\"top\"><p>&nbsp;</p></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"five\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><p>Rupees In Words : THREE THOUSAND THREE HUNDRED SIXTY SEVEN ONLY.</p></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"six\">\r\n");
      out.write("  <tr class=\"six_left\">\r\n");
      out.write("    <td><p>Received the Stock mentioned above in good condition.</p></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr class=\"six_right\">\r\n");
      out.write("    <td ><p>Purchaser's Signature</p></td>\r\n");
      out.write("    <td align=\"right\" valign=\"top\"><p>Authorised Signatory</p></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"seven\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td align=\"right\" valign=\"top\"><p>E.& O.E.</p></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table> <!-- containerend -->\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write(" <br/>\r\n");
      out.write("</div>\r\n");
      out.write("<input type=\"button\" onclick=\"printDiv('printableArea')\" value=\"print a div!\" /> \t         \r\n");
      out.write("</center></body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
