/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.44
 * Generated at: 2017-08-07 06:36:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.connection.account.ConnectionDAO;
import java.sql.*;

public final class layout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(12);
    _jspx_dependants.put("/Header/header.jsp", Long.valueOf(1501851873098L));
    _jspx_dependants.put("/Header/footer.jsp", Long.valueOf(1501496012435L));
    _jspx_dependants.put("jar:file:/D:/eclipse%20projects/pvs-inventory/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pvs-inventory/WEB-INF/lib/struts2-jquery-plugin-3.1.1.jar!/META-INF/struts-jquery-tags.tld", Long.valueOf(1313075066000L));
    _jspx_dependants.put("jar:file:/D:/eclipse%20projects/pvs-inventory/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pvs-inventory/WEB-INF/lib/struts2-core-2.2.1.jar!/META-INF/struts-tags.tld", Long.valueOf(1279356888000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1501496015675L));
    _jspx_dependants.put("jar:file:/D:/eclipse%20projects/pvs-inventory/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pvs-inventory/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-jquery-plugin-3.1.1.jar", Long.valueOf(1501496019268L));
    _jspx_dependants.put("jar:file:/D:/eclipse%20projects/pvs-inventory/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pvs-inventory/WEB-INF/lib/tiles-jsp-2.0.6.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1210694994000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.2.1.jar", Long.valueOf(1501496019190L));
    _jspx_dependants.put("jar:file:/D:/eclipse%20projects/pvs-inventory/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pvs-inventory/WEB-INF/lib/spring-security-taglibs-3.0.5.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1290065394000L));
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-2.0.6.jar", Long.valueOf(1501496020236L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-3.0.5.RELEASE.jar", Long.valueOf(1501496018832L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.connection.account.ConnectionDAO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005fgetAsString_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsj_005fhead_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifAnyGranted;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftiles_005fgetAsString_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsj_005fhead_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifAnyGranted = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftiles_005fgetAsString_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fsj_005fhead_005fnobody.release();
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifAnyGranted.release();
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>");
      if (_jspx_meth_tiles_005fgetAsString_005f0(_jspx_page_context))
        return;
      out.write("</title>\r\n");
      out.write("<!-- <script type=\"text/javascript\">\r\n");
      out.write("window.onbeforeunload = function (e)\r\n");
      out.write("{\r\n");
      out.write("\te = e || window.event;\r\n");
      out.write("\te.returnValue=\"You want to leave\";\r\n");
      out.write("};\r\n");
      out.write("</script>-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>Header</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/style.css\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/packed.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/tinydropdown.js\"></script>\r\n");
      if (_jspx_meth_sj_005fhead_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');

	String a1 = (String) session.getAttribute("user");
	
	try
	{
		if(a1.compareTo("null")==0)
		response.sendRedirect("login.jsp");
	}
	catch(Exception e)
	{
		response.sendRedirect("login.jsp");
	}
	
	String a3 = "", a4="",a5="",a6="";
	String sql = "select * from logins where USERNAME ='" + a1 + "'";

	Connection conn = ConnectionDAO.getConnectionObject();
	Statement stm = ConnectionDAO.createStatement(conn);
	try {

		ResultSet rs = stm.executeQuery(sql);
		while (rs.next()) {

			a3 = rs.getString(6);
			
		}
		
	sql = "select * from user where USERNAME ='" + a1 + "'";
	rs = stm.executeQuery(sql);
		while (rs.next()) {

			a6 = rs.getString(2);
			
		}
	} catch (SQLException e) {
		e.printStackTrace();
	}

	ConnectionDAO.closeConnection(conn);
	//System.out.printf("UserName: " + a3);

      out.write('\r');
      out.write('\n');

String cmp=(String) session.getAttribute("cmp");
String fin=(String) session.getAttribute("fin");
Connection conn1 = ConnectionDAO.getConnectionObject();
Statement stm1 = ConnectionDAO.createStatement(conn1);
String add1="",add2="";
try
{
	ResultSet rs;
	sql="select * from company_master where company_name='"+cmp+"'";
	//System.out.println(sql);
	rs=stm1.executeQuery(sql);
	while(rs.next())
	{
		add1=rs.getString(4);
		add2=rs.getString(5);
	}
	session.setAttribute("ad1",add1);
	session.setAttribute("ad2",add2);
	ConnectionDAO.closeConnection(conn1);
}
catch(Exception fff)
{
	System.out.println("error on address getting "+fff);
}

      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body >\r\n");
      out.write("\t<table width=\"100%\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div align=\"center\" >\r\n");
      out.write("\t\t\t\t\t<p class=\"style3\">\r\n");
      out.write("\t\t\t\t\t ");
      out.print(cmp );
      out.write(" </p>\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t <p class=\"style3_0\">\r\n");
      out.write("\t\t\t\t\t");
      out.print(add1 );
      out.write("<br>\r\n");
      out.write("\t\t\t\t\t");
      out.print(add2 );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t <p style=\"color:darkgreen\">\r\n");
      out.write("\t\t\t\t\tFinancial Year: <u>");
      out.print(fin );
      out.write("</u></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<table width=\"100%\" >\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td valign=\"bottom\">\r\n");
      out.write("\t\t\t\t<div align=\"right\" class=\"style6\">\r\n");
      out.write("\t\t\t\t\tWelcome&nbsp; <span style=\"color: red\">");
      out.print(a3 );
      out.write("</span><a\r\n");
      out.write("\t\t\t\t\t\thref=\"logout\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"text-decoration: none\"> <span style=\"color: green;\"><strong>Logout</strong></span></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div class=\"nav1\">\r\n");
      out.write("\t\t<ul id=\"menu\" class=\"menu\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar dropdown = new TINY.dropdown.init(\"dropdown\", {\r\n");
      out.write("\t\t\tid : 'menu',\r\n");
      out.write("\t\t\tactive : 'menuhover'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<br/><br/>\r\n");
      out.write("<div style=\"display: block;height:100%;padding-bottom: 20px;overflow:auto;\">");
      if (_jspx_meth_tiles_005finsertAttribute_005f0(_jspx_page_context))
        return;
      out.write("</div>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>Footer</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Keep the http-equiv meta tag for IE8 -->\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=8\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Link the CSS file here -->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/style.css\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- END OF PULL DOWN MENU -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"footer\"\r\n");
      out.write("\t\tstyle=\"clear: both; text-align: center; font-size: 11px;background-color:#F4BD58;\">\r\n");
      out.write("\t\t<marquee behavior=\"scroll\" direction=\"left\" scrollamount=\"1\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<p>Designed & Developed By:- <a href=\"http://www.brandmehigh.in\" target=\"new\">BrandMeHigh</a></p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</marquee>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tiles_005fgetAsString_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:getAsString
    org.apache.tiles.jsp.taglib.GetAsStringTag _jspx_th_tiles_005fgetAsString_005f0 = (org.apache.tiles.jsp.taglib.GetAsStringTag) _005fjspx_005ftagPool_005ftiles_005fgetAsString_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.GetAsStringTag.class);
    boolean _jspx_th_tiles_005fgetAsString_005f0_reused = false;
    try {
      _jspx_th_tiles_005fgetAsString_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005fgetAsString_005f0.setParent(null);
      // /Layout/layout.jsp(5,7) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005fgetAsString_005f0.setName("title");
      int _jspx_eval_tiles_005fgetAsString_005f0 = _jspx_th_tiles_005fgetAsString_005f0.doStartTag();
      if (_jspx_th_tiles_005fgetAsString_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftiles_005fgetAsString_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005fgetAsString_005f0);
      _jspx_th_tiles_005fgetAsString_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tiles_005fgetAsString_005f0, _jsp_getInstanceManager(), _jspx_th_tiles_005fgetAsString_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sj_005fhead_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sj:head
    com.jgeppert.struts2.jquery.views.jsp.ui.HeadTag _jspx_th_sj_005fhead_005f0 = (com.jgeppert.struts2.jquery.views.jsp.ui.HeadTag) _005fjspx_005ftagPool_005fsj_005fhead_005fnobody.get(com.jgeppert.struts2.jquery.views.jsp.ui.HeadTag.class);
    boolean _jspx_th_sj_005fhead_005f0_reused = false;
    try {
      _jspx_th_sj_005fhead_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sj_005fhead_005f0.setParent(null);
      int _jspx_eval_sj_005fhead_005f0 = _jspx_th_sj_005fhead_005f0.doStartTag();
      if (_jspx_th_sj_005fhead_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsj_005fhead_005fnobody.reuse(_jspx_th_sj_005fhead_005f0);
      _jspx_th_sj_005fhead_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sj_005fhead_005f0, _jsp_getInstanceManager(), _jspx_th_sj_005fhead_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.AuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.AuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifAnyGranted.get(org.springframework.security.taglibs.authz.AuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f0.setParent(null);
      // /Header/header.jsp(123,4) name = ifAnyGranted type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f0.setIfAnyGranted("ROLE_ADMIN");
      int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t\t<li><a href=\"#\">Master Management</a>\r\n");
          out.write("\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t<li><a>Account Management</a>\r\n");
          out.write("\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"acgrouplist\">Group Master</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"grpnamelist\">SubGroup Master</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"ledgerlist\">Ledger Master</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"narrationlist\">Narration Master</a></li>\r\n");
          out.write("\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t<li><a>Inventory Management</a>\r\n");
          out.write("\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"categorylist\">Party Category Master</a></li>\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"salesmanlist\">Sales Man Master</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"compdetaillist\">Company Master</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"placemasterlist\">Area Master</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t<!-- <li><a href=\"partymasterlist\">Party Master</a></li> -->\r\n");
          out.write("\t\t\t\t\t\t<!-- \t<li><a href=\"materialgrouplist\">Material Group Master</a></li> -->\r\n");
          out.write("\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"claimlist\">Claim Master</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"partydetaillist\">Party Master</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"materialglist\">Material Group Master</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"materialpaddarlist\">Material Master Creation</a></li>\r\n");
          out.write("\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t<li><a href=\"#\">Transaction Management</a>\r\n");
          out.write("\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t<li><a>Account Transaction</a>\r\n");
          out.write("\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"receiptlist\">Receipt</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"paymentlist\">Payment</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"contralist\">Contra</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"journallist\">Journal</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"debitnotelist\">Debit Note</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"creditnotelist\">Credit Note</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"saleslist\">Credit Sales</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"purchaselist\">Credit Purchase</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"cashsaleslist\">Cash Sales</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"cashpurchaselist\">Cash Purchase</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"bankreconsiliation\">Bank Reconciliation</a></li>\r\n");
          out.write("\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t<li><a>Inventory Transaction</a>\r\n");
          out.write("\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a>Purchase Entry</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"purchaselist1\">Purchase Credit Bill</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"purchaseretlist\">Purchase Cash Bill</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t</li>\t\r\n");
          out.write("\t\t\t\t\t\t\t<li><a>Sales Memo Entry</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"csalesmemeoentry\">Sales Memo(Counter)</a>\t</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"salesmemeoentry\">Sales Memo(Outside)</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"msalesmemeoentry\">Sales Memo(MRP)</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"dsalesmemeoentry\">Sales Memo(Distributor)</a></li>\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t </li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"salesreturn\">Amend Sales Memo</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"salesreturn\">Loading Chart</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"salesreturn\">Sales Summary</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"salesreturn\">Sales Memo Update</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"salesreturn\">Collection Entry</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"salesreturn\">Sales Return</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"salesreturn\">Debit Note</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"salesreturn\">Credit Note</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t</li>\t\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t<li><a href=\"#\">Report Management</a>\r\n");
          out.write("\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t<li><a>Account Report</a>\r\n");
          out.write("\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"cashlist\">Daily Cash Balance</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"partyledgerlist\">Monthly Breakup of Party Ledger</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a>Detail Trial Balance</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"grouptriallist\">Group Trial Balance</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"subgrouptriallist\">Sub-Group Trial Balance</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"triallist\">Ledger Trial Balance</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"openingtriallist\">Opening Trial Display</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"cashbooklist1\">Cash Book Display</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"bankbooklist\">Bank Book Display</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"cashtriallist\">Cash Trial Display</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"statementlist\">Statement Of Account</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"maintainlist\">Maintain Voucher Transaction</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"billoutstandinglist\">Bill Outstanding</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"bankreconciliationreport\">Bank Reconciliation Report</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"daybooklist\">Day Book</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"journalregisterlist\">Journal Register</a></li>\r\n");
          out.write("\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t<li><a>Inventory Report</a>\r\n");
          out.write("\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a>Material Ledger</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"\">Material Wise</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"\">Batch Wise</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a>Stock Statement</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"\">Sales & Stock Statement</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a>Consolidation Statement</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">Consolidation Statement</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">Consolidation Statement & Bonus</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">Month/Sales & Coll</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"\">Batch Wise Stock</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"\">Bonus Statement</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"\">SPL. Free Report</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a>Stock Status</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"\">Purchase Rate Wise</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"\">Sales Rate Wise</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a>Sales Report</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"\">Representative Oftake</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"\">Lifting Summary</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"\">Party Lifting</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"\">A.S.M Lifting</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t\t<li><a>Registers</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a>Sales Return Register</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">Company Wise</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">For All Company</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a>Purchase Register</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">Purchase Details</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">Purchase Report</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a>Outward Register</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">Company Wise</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">Company & Party Details</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">Company & Party Report</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">Company Wise Detail</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">Company Wise Report</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a>Inward Register</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">Inward Details</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">Inward Report</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a>Sales Register</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">Company Wise</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">All Company</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">Party Wise</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"\">Other Sales Registration</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a>GRB Register</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">Company & Party Detail</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">Company Wise Details</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"\">Company Wise Report</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t<li><a href=\"#\">System Management</a>\r\n");
          out.write("\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t<li><a href=\"calculator\">Calculator</a></li>\r\n");
          out.write("\t\t\t\t\t<li><a href=\"userlist\">User Profile </a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t</ul></li>\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t<li><a href=\"#\">Dash Board </a>\r\n");
          out.write("\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t<li><a href=\"dashboard\">Dashboard</a></li>\r\n");
          out.write("\t\t\t\t\t\r\n");
          out.write("\t\t\t\t</ul></li>\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_sec_005fauthorize_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifAnyGranted.reuse(_jspx_th_sec_005fauthorize_005f0);
      _jspx_th_sec_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f0 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    boolean _jspx_th_tiles_005finsertAttribute_005f0_reused = false;
    try {
      _jspx_th_tiles_005finsertAttribute_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005finsertAttribute_005f0.setParent(null);
      // /Layout/layout.jsp(18,76) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f0.setName("body");
      int _jspx_eval_tiles_005finsertAttribute_005f0 = _jspx_th_tiles_005finsertAttribute_005f0.doStartTag();
      if (_jspx_th_tiles_005finsertAttribute_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f0);
      _jspx_th_tiles_005finsertAttribute_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tiles_005finsertAttribute_005f0, _jsp_getInstanceManager(), _jspx_th_tiles_005finsertAttribute_005f0_reused);
    }
    return false;
  }
}
